apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate-sample
spec:
  dnsNames:
    - test.example.com
  issuerRef:
    group: certmanager.example.com
    kind: LocalCA
    name: localca-sample
  secretName: certificate-sample-tls
